- name: "copy files to server into {{remote_dir}}"
  copy: 
    src: "{{ role_path }}/files/"
    dest: "{{remote_dir}}"

- name: "copy config template to {{remote_dir}}"
  template:
    src: feed2toot.ini
    dest: "{{remote_dir}}"

- name: install poetry
  shell: curl -sSL https://install.python-poetry.org | python3 -

- name: install dependencies
  shell: "{{poetry_bin}} install --no-dev"  
  args:
    chdir: "{{remote_dir}}"

- name: install cronjob
  cron: 
    name: cronjob for regular mediacccde toots
    special_time: "hourly"
    # https://feed2toot.readthedocs.io/en/latest/use.html
    job: "cd {{remote_dir}} && {{poetry_bin}} run feed2toot -c feed2toot.ini"
